role_key_sign:
  path: /role/key/sign
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\SecurityHttpService::sign'

role_key_verify:
  path: /role/key/verify
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\SecurityHttpService::verify'

role_key_rotate:
  path: /role/key/rotate
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\SecurityHttpService::rotate'

role_key_jwks_get:
  path: /role/key/jwks
  methods: [ GET ]
  controller: 'App\Rolling\Service\Http\Role\Api\SecurityHttpService::jwksGet'

role_key_jwks_put:
  path: /role/key/jwks
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\SecurityHttpService::jwksPut'
