role_pdp_batch:
  path: /pdp/batch
  controller: App\Rolling\Http\Role\Pdp\BatchController::post
  methods: [ POST ]

role_pdp_stream:
  path: /pdp/stream
  controller: App\Rolling\Http\Role\Pdp\StreamController::post
  methods: [ POST ]
