role_rebac_write:
  path: /v2/rebac/tuple/write
  methods: [ POST ]
  controller: App\Rolling\Controller\V2\RebacController::write

role_rebac_check:
  path: /v2/rebac/check
  methods: [ POST ]
  controller: App\Rolling\Controller\V2\RebacController::check
