role_policy_get_draft:
  path: /role/policy/draft
  methods: [ GET ]
  controller: 'App\Rolling\Service\Http\Role\Api\PolicyHttpService::getDraft'
role_policy_put_draft:
  path: /role/policy/draft
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\PolicyHttpService::putDraft'
role_policy_publish:
  path: /role/policy/publish
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\PolicyHttpService::publish'
role_policy_effective:
  path: /role/policy/effective
  methods: [ GET ]
  controller: 'App\Rolling\Service\Http\Role\Api\PolicyHttpService::getEffective'
