role_admin_start:
  path: /v2/admin/approval/start
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::start'

role_admin_approve:
  path: /v2/admin/approval/approve
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::approve'

role_admin_reject:
  path: /v2/admin/approval/reject
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::reject'

role_admin_delegate:
  path: /v2/admin/delegate
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::delegate'

role_admin_override:
  path: /v2/admin/override
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::override'
