role_eval_one:
  path: /v2/role/eval
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\EvalHttpService::eval'

role_eval_batch:
  path: /v2/role/eval-batch
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\EvalHttpService::evalBatch'
