role_approval_start:
  path: /role/approval/start
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::start'

role_approval_approve:
  path: /role/approval/approve
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::approve'

role_approval_reject:
  path: /role/approval/reject
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::reject'

role_delegation_create:
  path: /role/delegation/create
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::delegate'

role_override_create:
  path: /role/override/create
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\AdminHttpService::override'
