role_obligation_apply:
  path: /role/obligation/apply
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\ObligationHttpService::apply'

role_obligation_check:
  path: /role/obligation/check
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\ObligationHttpService::checkAndApply'
