role_eval_run:
  path: /role/eval/run
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\EvalHttpService::eval'

role_eval_batch:
  path: /role/eval/batch
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\Api\EvalHttpService::evalBatch'
