role_pdp_batch:
  path: /pdp/batch
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\V2\AccessHttpService::checkBatch'

role_pdp_stream:
  path: /pdp/stream
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\V2\BulkHttpService::stream'
