role_policy_get_draft:
  path: /v2/role/policy/draft
  controller: App\Http\Role\Api\PolicyController::getDraft
  methods: [ GET ]
role_policy_put_draft:
  path: /v2/role/policy/draft
  controller: App\Http\Role\Api\PolicyController::putDraft
  methods: [ POST ]
role_policy_publish:
  path: /v2/role/policy/publish
  controller: App\Http\Role\Api\PolicyController::publish
  methods: [ POST ]
role_policy_effective:
  path: /v2/role/policy/effective
  controller: App\Http\Role\Api\PolicyController::getEffective
  methods: [ GET ]
