role_access_check:
  path: /role/access/check
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\V2\AccessHttpService::check'

role_access_batch:
  path: /role/access/batch
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\V2\AccessHttpService::checkBatch'
