role_obligations_apply:
  path: /v2/obligations/apply
  controller: App\Controller\Api\ObligationController::apply
  methods: [ POST ]

role_check_oblige:
  path: /v2/check/oblige
  controller: App\Controller\Api\ObligationController::checkAndApply
  methods: [ POST ]
