role_eval_one:
  path: /v2/role/eval
  controller: App\Rolling\Controller\Api\EvalController::eval
  methods: [ POST ]

role_eval_batch:
  path: /v2/role/eval-batch
  controller: App\Rolling\Controller\Api\EvalController::evalBatch
  methods: [ POST ]
