role_rebac_write:
  path: /v2/rebac/tuple/write
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\V2\RebacHttpService::write'

role_rebac_check:
  path: /v2/rebac/check
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\V2\RebacHttpService::check'
