role_access_check:
  path: /v2/access/check
  controller: App\Integration\Symfony\Controller\RoleApiV2Controller::check
  methods: [ POST ]

role_access_check_batch:
  path: /v2/access/check:batch
  controller: App\Integration\Symfony\Controller\RoleApiV2Controller::checkBatch
  methods: [ POST ]
