role_access_check:
  path: /v2/access/check
  controller: App\Rolling\Controller\V2\AccessController::check
  methods: [ POST ]

role_access_check_batch:
  path: /v2/access/check:batch
  controller: App\Rolling\Controller\V2\AccessController::checkBatch
  methods: [ POST ]
