role_relation_write:
  path: /role/relation/write
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\V2\RebacHttpService::write'

role_relation_check:
  path: /role/relation/check
  methods: [ POST ]
  controller: 'App\Rolling\Service\Http\Role\V2\RebacHttpService::check'
