rolling_admin_easyadmin:
  resource: 'routes/rolling_admin_easyadmin.yaml'
  prefix: /ea

role_public_business:
  resource: 'routes/role_public.yaml'

role_admin_business:
  resource: 'routes/role_business_admin.yaml'
  prefix: /ea

role_ops_business:
  resource: 'routes/role_ops.yaml'
  prefix: /ea
