services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\Command\:
    resource: '../src/Command/'

  App\Infrastructure\Observability\Metrics\:
    resource: '../src/Infrastructure/Observability/Metrics/'


  App\Service\:
    resource: '../src/Service/'

  App\Infrastructure\Rebac\InMemoryTupleStore: ~
  App\InfrastructureInterface\Rebac\TupleStoreInterface: '@App\Infrastructure\Rebac\InMemoryTupleStore'

  App\Integration\Symfony\DemoPdpV2: ~

  App\ServiceInterface\Policy\PdpV2Interface: '@App\Integration\Symfony\DemoPdpV2'
