version: "3.9"
services:
  api:
    image: php:8.2-cli
    container_name: role_api
    command: [ "php","-S","0.0.0.0:8080","-t","/app/public","/app/public/index.php" ]
    volumes: [ "${APP_SRC:-.}:/app", "./kit_mount:/kit:ro" ]
    ports: [ "8080:8080" ]
  opa:
    image: openpolicyagent/opa:0.63.0
    container_name: role_opa
    command: [ "run","--server","-a",":8181","/policy" ]
    volumes: [ "./opa/policy:/policy:ro" ]
    ports: [ "8181:8181" ]
